version: '3.9'

volumes:
    data_storage:

services:
    db:
        image: mysql
        container_name: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db_test
            MYSQL_USER: user
            MYSQL_PASSWORD: paris
            MYSQL_ROOT_PASSWORD: paris
        volumes:
            - data_storage:/var/lib/mysql
        networks:
            - default